### PR TITLE
Include more functionality and better interface for the app

### PR DESCRIPTION
**Pull request by quinor**
This version of the code is still rough but should work and provide reasonable interface with more options.

Major TODOs (added on top of existing ones):
- fix preview bounding box (dashed line) to be tight around the picture instead of max available size - this bounding box is supposed to be the same as what `--box` will trace
- make the app robust against multiple people using it at once (session-like mechanism)
- better communication with the C++ driver (ie. make it return json with information)
- make UI less ugly as fuck

### CODE REVIEW

**Review by CriMilanese — CHANGES_REQUESTED** [review]
more PRs would have been easier to manage, I will cherry-pick some of these commits.

**Comment by quinor** [comment]
> more PRs would have been easier to manage, I will cherry-pick some of these commits.

I rewrote most of the app. Wasn't sure how to split it into commits.

**Comment by CriMilanese** [comment]
included all your commits, please be a little kinder with commit messages such as "ugly as fuck"

**Comment by quinor** [comment]
> included all your commits, please be a little kinder with commit messages such as "ugly as fuck"

Sorry! I was just slightly annoyed with my own "pretty web" skills. I did not mean to make any comments towards anyone's work except my own!

**Pull request closed without merging**
